# Generated by Django 5.0.2 on 2024-02-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='userid',
        ),
    ]
