# Generated by Django 5.0.2 on 2024-03-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_user_profile_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
