# Generated by Django 5.0.2 on 2024-03-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_user_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={},
        ),
    ]
